### ISSUE TITLE
Screen thumbnails UI refinements

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#102]
Some suggestions to consider:

- Move the right click menus of thumbnails into a sort of dropdown menu, which shows up only on mouse over (the little triangle on the mockup I sent you earlier) Makes it easier to discover, that there is a menu there.
- Add a hover effect for the text itself to indicate that it is clickable/editable: maybe a thin grey border for example, or a darker gray bg
- Center the screen name under the thumbnail
- Center the plus sign vertically

**Comment by nurpax** [comment]
Something like this maybe: https://youtu.be/zIxlxf4K6zo

This implements bullets 2 and 4.  Not keen on 3 -- I tried it earlier but it looks ugly when the name input box is activated (centering changes as you type in a longer string).

Also didn't do 1, at least not yet.  Seems also like a good idea, just not as trivially low hanging fruit as these other changes.

**Comment by Esshahn** [comment]
I'd recommend let's close this in favor of other interesting tasks to focus on.
It's mostly cosmetic anyway.
