### ISSUE TITLE
Certain characters are avoided in the character palette

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#103]
If I move with the wasd keys, there are certain charcters which are... avoided by the program. Eiither just skips over them, or literaly goes around them.

I made a video: https://drive.google.com/file/d/1SpoJN3Q-s0P5Tt4G8PysX5zN7Hu7klZV/view?usp=sharing

In the first part of the video, I just move left and right with the a and d keys. There are chars which skipped. The keypress seems to be swallowed - so I press the key, nothing happens, then press the key again, and the selection jumps over one character.
In the second half, I move up and down with the w and s keys, and the selection just goes around the problematic character without me touching any of the a or d keys.

I can't repro yet unfortunately, but this is not the first occurence.

**Comment by nurpax** [comment]
Any chance you pressed 'r' to rotate the current char?  It could be something related to the char rotation code..

**Comment by nurpax** [comment]
Yeah I just reproed it.. Thanks for reporting it, I wasn't aware of this.

I can easily trigger it by pressing 'r' on some char that can be rotated and then moving around with wasd.

This is a really funny bug. :)

**Comment by nurpax** [comment]
Oh, it doesn't even need 'r'.  Repros from clean state without any rotation business. WTF

**Comment by Viza74** [comment]
Hmm, it is nice to have a repro, but I'm reasonably sure that I did not rotated characters... There is a small chance that I did accidentally, but definitely not intentionally.

**Comment by Viza74** [comment]
ohh, your comment just jumped in front of mine :)

**Comment by Esshahn** [comment]
great work guys!
