### ISSUE TITLE
Add new screens on the left side, not the right

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#116]
Imagine you work with a lot of screens like I usually do. 
I duplicate a screen to save the current state in case I mess up and want to go back.
Now when I duplicate a screen, it gets added to the right side, hence I need to move the screen area every single time to put my current screen into the visible area again.

Solution:
Add new screens on the left side. This makes sure that the newest screen is always on the left, always in the same spot (helping the user to orient himself better). Older screens naturally disappear into the invisible area when they hit the border on the right side.

**Comment by Esshahn** [comment]
one more upside of this change: the "+" icon could stay on the left side and would not move anymore when new screens are added, making UI more consistent.

**Comment by Esshahn** [comment]
noticed even another advantage - when loading a file it would display the newest screen, not the oldest :D

**Comment by nurpax** [comment]
Here's one way to do it, IMO this works pretty ok.

I'm somewhat against changing the order of screens completely but this new thing I added probably strikes a reasonable compromise.

https://twitter.com/nurpax/status/1065754758437380098

**Comment by nurpax** [comment]
I'm closing this to make the 0.5 list short.  I'm not entirely convinced that this is needed, I kind of like it the way it is now.
