### ISSUE TITLE
Char rotation not working in all cases

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#117]
For most of the time, character rotation is nothing less than amazing.
Fantastic work here Janne, loving it!

I noticed that the normal diagonals

![screenshot 2018-09-06 um 22 26 48](https://user-images.githubusercontent.com/434355/45183302-01966380-b224-11e8-8589-fbfb3f4c9d3c.jpg)

do not rotate with their inverse versions

![screenshot 2018-09-06 um 22 26 56](https://user-images.githubusercontent.com/434355/45183315-09560800-b224-11e8-91fa-6ba9dc68543f.jpg)

Is that doable?

**Comment by nurpax** [comment]
Only bit exact transformations are considered as a match when finding the rotated screencode.  I imagine the above is not exactly a rotate version of the other, so it can't find a match.  So if we wanted this, would need to add some sort of fuzzy logic to finding the match.  Seems like that'd open a can of worms in terms of heuristics.

**Comment by Esshahn** [comment]
You are right! I never noticed the difference, the lower ones do have a pixel less.
