### ISSUE TITLE
File -> New

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#118]
Seems like we don't have a File -> New yet!
Probably because we used the "clear" tool for starting from scratch, but with multiple screen support, this would no longer work.

Suggested:
* File -> New
* Modal "Are you sure?" YES/NO
* yes -> start with clean state (including all undo)
* no -> no change

**Comment by nurpax** [comment]
Is this acceptable?

https://youtu.be/ZZcP5CnwGrY

**Comment by Esshahn** [comment]
perfect
