### ISSUE TITLE
Enabling Caps lock disables shortcuts

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#119]
...or probably more accurately the app now receives uppercase characters as shortcuts, so it is not reacting to them...
I don't know if this is a bug. I guess Shift+keys should be a legal shortcut, so technically capslock+key sends that, but still it feels like a bug. :)
Guess the fix would depend on if it is possible for you to differentiate a capslock+key from a shift+key in the program.

**Comment by nurpax** [comment]
Petmate checks for lowercase characters in the shortcut code. Shift is tracked as a separate keystate sl it should be enough to simply inputkey.toLowerCase() before checking sny shortcuts.
