### ISSUE TITLE
Save as executable binary

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#12]
Save the file as a .prg file that can be executed on the C64

**Comment by nurpax** [comment]
Simple display of one screen is fortunately easy..  I'm planning to compile just a .prg and patch the content into a binary template (so there's no need to compile any asm source).

But prg output could potentially include some fancy things like playing a sid + supporting multiple screens in a slideshow.

**Comment by nurpax** [comment]
All export types (https://github.com/nurpax/petmate/issues/13, BASIC, etc.) should probably open up some kind of options pane that could be used to set export settings.
