### ISSUE TITLE
Drag and zoom canvas

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#122]
Shortcut suggestions:
middle mouse drag - drag canvas
mouse wheel - zoom canvas

And/or alternative controls:
space+left mouse drag - drag canvas
alt+space+left mouse drag - zoom canvas

These are more-or-less Photoshop shortcuts - at least what I'm using in Photoshop :)

I guess the scrollbars could stay even with these controls, if for nothing else, just to provide orientation for the user about the windows position/zoom in the full picture.
Maybe the best would be those kind of scroolbars which are defualt very thin, and get thicker on mouse hover. So it is generaly out of way, but if somebody for some pervert reason still want to use them, they are there. :)
Maybe with a global app preference to enable/disable scrollbars altogether.
But I think just plain old regular scroolbars, or non-interactive thin scrollbarlike indicators would be perfectly good too.

Ohh, maybe a couple of less important shortcuts/functions:
ctrl+0 - fit all to screen 
ctrl+1, ctrl+2, ctrl+3, ctrl+4 - zoom to 100, 200, 300, 400 percent

**Comment by Esshahn** [comment]
Recommending closing in favor of https://github.com/nurpax/petmate/issues/20

**Comment by nurpax** [comment]
This should be kept open.  @Viza74 's lists shortcuts that I currently implemented a little differently.  Having a pan/zoom "tool" might not be the best thing here but rather just keep pan/zoom available via pressing "spacebar" always (like in Photoshop, as far as I know).

**Comment by nurpax** [comment]
Closing in favor of https://github.com/nurpax/petmate/issues/142 (where I summarized my remaining tasks into a checklist)
