### ISSUE TITLE
error when renaming screens starting a number

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#124]
Reproduce

* click on a thumbnail name to edit it
* enter a number
* press return

Result

![screenshot 2018-11-22 um 15 02 41](https://user-images.githubusercontent.com/434355/48907469-d6f19980-ee67-11e8-9209-f57053ef0c63.jpg)

**Comment by nurpax** [comment]
We decided in an earlier issue that we should only allow screen names that are not valid assembler/C symbol names. 

Maybe that’s too strict and we should just let .asm exported petscii fail to compile. 

I guess I’d slightly prefer to just let compilation break. Doesn’t seem like a big deal — programmers should be able to figure it out if they look at the exported file.
