### ISSUE TITLE
Feature Request: Combine Color RAM Values

### ISSUE THREAD

**Issue by c64whiz** [nurpax/petmate#126]
So, I know this is a bit of a specialized request, but figured I'd put the thought into your mind just in case you were interested.

As you know, Color RAM will only look at the low nibble to determine color, leaving the high nibble wasted.  When you create, say 4 screens, the typical setup requires roughly 8000 bytes (4000 for characters + 4000 for colors).  However, if an export option allowed us to "combine" color screen data, we can save 25%.  For example, 4 screens would require 4000 bytes for characters, but only 2000 bytes for colors; screen 1 colors are the low nibbles, screen 2 colors are the high nibbles (1000 bytes), and same for screens 3 and 4 (another 1000 bytes).  This example saves 2K...a whole screen worth...chars and colors!

The cost is a little extra processing:
```
            ldx #$01         ; Some flag: 0 to use low nibble; 1 to use high nibble
            lda cvalue       ; Color value from the .byte statements exported
            cpx #$01
            beq set_color    ; if 0, just use the low nibble as normal
            lsr A            ;  else, move high nibble to low nibble
            lsr A
            lsr A
            lsr A
set_color:
            ; continue as normal
```
So for an extra 10 bytes of processing, we can save 25% storage RAM.  I'm working on my own Perl script to convert the current .asm export (for KickAssembler) to support this, but again, thought I'd put the idea in your head as it may be easier to implement during export.

Thanks!

--C64Whiz

**Comment by nurpax** [comment]
Thanks for the report -- it's a nice & cheap compression scheme!  IMO this gets into a bit ambiguous territory.

It's possible to pretty easily read .petmate files directly in Perl (or maybe even in KickAssembler, certainly trivially in my own assembler c64jasm) which then enables any type of preprocessing of PETSCII data.  The .petmate files are just JSON so it's easy to read them.  Or alternatively, add JSON export which saves just screencodes, colors and bg/border colors in an even simpler JSON format.
