### ISSUE TITLE
Save as assembly source

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#13]
Save the file as assembly source for

- kickass
- ACME
- more?

**Comment by nurpax** [comment]
KickAssembler format is done.  I don't use ACME so not sure how to format it.  Patches/examples are welcome. Or a translation of Kickass .asm to ACME.

**Comment by Esshahn** [comment]
ACME is super simple, just take care of labels and the data prefix

"loop:" becomes "loop" (drop the colon)
".byte" becomes "!byte"

That should be all, if you avoid the fancy stuff like macros.
