### ISSUE TITLE
Toggle to display a 8x8 grid

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#134]
Would be cool to have a grid that can help distinguish the characters. Should be an on/off toggle, like "shift + G" or similar.

**Comment by nurpax** [comment]
You mean like `g`?

**Comment by Esshahn** [comment]
Feature requests should always be implemented this quick!!!1

**Comment by Esshahn** [comment]
I knew it was in there. Knew it. Pressed G, nothgin happend, rage posted new issue.
I'm dumb. Cheers.!

**Comment by nurpax** [comment]
You requested it 6 months ago https://github.com/nurpax/petmate/issues/16 :)

**Comment by Esshahn** [comment]
Finally some proof how long my memory goes back.
