### ISSUE TITLE
custom canvas: big numbers crash petmate

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#137]
Petmate can be crashed if numbers for the canvas are too big, e.g. setting

99999x232323

Recommendations:
- do not accept numbers too big
- convert too big numbers to the highest allowed one automatically

**Comment by nurpax** [comment]
Thanks for reporting this!  Someone had to have the courage to try what happens.  I set the max to 1024x1024 now.  Even that feels a bit like zooming into a fractal..

**Comment by nurpax** [comment]
The input form just clamps the values.  Doesn't give any kind of an error.  Pretty sure that's ideal.  Error messages are always kind of scary.
