### ISSUE TITLE
off by one bug in either SEQ import or export

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#152]
Either the .seq export or import (or both :)) have an off by one bug.  The last row of the PETSCII screen gets duplicated and looks like the image is shifted up by one row.

Here's a .petmate file that contains content on all the 25 rows.  Screenshot how it's supposed to look like and how it goes wrong when imported (look at the last two rows).  Also attached the exported seq file.

How it's supposed to work:

![seqbug1-working](https://user-images.githubusercontent.com/297823/56613436-4b02ba00-661f-11e9-8dc5-9a6b20abc0bd.png)

How it looks like after exporting to SEQ and then importing the SEQ:

![seqbug1-after-import](https://user-images.githubusercontent.com/297823/56613626-b0ef4180-661f-11e9-9aa3-e698a5268579.png)

Here's the petmate file and the exported seq:

[attachments.zip](https://github.com/nurpax/petmate/files/3109444/attachments.zip)

**Comment by sixofdloc** [comment]
Without looking, I'd guess that's what's happening is that scrollup (triggered when you hit the bottom/right corner) in the import isn't clearing the bottom screen row the way the c64 would.  The way I see it, there are two possible useful fixes - 1. add an exception to scrollup so it doesn't fire on the last character in a file (or at least clears the bottom row when it fires), or 2. implement the expanding file patch we discussed in email?

**Comment by nurpax** [comment]
Yes I think there's a scroll up that shouldn't happen. But clearing the last row won't fix it as the screen has already been shifted up by one row, meaning we've lost the first row of the image.

**Comment by sixofdloc** [comment]
On the actual C64, the behavior would be that it scrolls the screen up by one row and leaves a blank row at the bottom.  That's clearly not ideal here :)   Shall I add a hook to suppress the scrollup if it's on the last character of a file?

**Comment by nurpax** [comment]
@sixofdloc https://github.com/nurpax/petmate/pull/154 seems to fix it.

**Comment by nurpax** [comment]
Makes sense.  I guess my change to suppress the "cursor right" on the last SEQ byte works fine then.

**Comment by sixofdloc** [comment]
On to expanding the screen for larger files, then?

**Comment by nurpax** [comment]
Yeah, that should work by just appending new rows instead of scrolling up.  But I'll merge my current fix for now.
