### ISSUE TITLE
wrong character as a result of .seq export & import

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#158]
If I export @manuelvio 's King image as .seq and then import it back, some characters change.

Here are the screenshots.  Note the appearance of "pi" characters in the left eye.

Any ideas @sixofdloc or @manuelvio?

Original:

![image](https://user-images.githubusercontent.com/297823/57556532-ff227580-737f-11e9-88f1-91212dcfdecc.png)

Export/imported:

![image](https://user-images.githubusercontent.com/297823/57556575-106b8200-7380-11e9-8183-b1f281ae2232.png)

**Comment by sixofdloc** [comment]
It traces back to a bug in https://github.com/sixofdloc/PETSCII2SEQ/blob/master/petout.c
There are a few exceptions it needs, line 130 should add 0x40, not 0x80, I believe.  I'll have to manually test every possible char.

**Comment by nurpax** [comment]
I guess one could have an automated test that generates all possible screen code combinations, converts to seq and imports the seq and checks that the two match?

**Comment by manuelvio** [comment]
Good catch. Definitely +1 for the automated test, I'll check the chars too and send a PR.
