### ISSUE TITLE
seq "Optimize sequence" option breaks the image

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#159]
This is what I get when I export with "Optimize sequence" and re-import.

@manuelvio, any ideas?

![image](https://user-images.githubusercontent.com/297823/57557132-a653dc80-7381-11e9-8f7b-68b58fa49b0a.png)

**Comment by manuelvio** [comment]
Poor Dave, nope, I have to re-check what causes this issue. At first sight it could be an odd use of blanks in original screen, since they're the ones being erased.

**Comment by manuelvio** [comment]
Ok, I got it. Blanks in the middle of the screen were reinserted without checking current reverse status, thus becoming reversed blanks in some lines, namely where previous char was reversed.

Inner blank blocks should be inserted with a proper 0x92 code where needed, as in the screen below:

![petmate_enjoy](https://user-images.githubusercontent.com/796799/57587786-2b1e3200-750b-11e9-93ad-807346b74963.png)

**Comment by nurpax** [comment]
fixed by @manuelvio, see #160
