### ISSUE TITLE
Toggle grid on/off

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#16]
A grid is always very helpful.

**Comment by nurpax** [comment]
@Esshahn should the grid for the drawing screen be an alpha blended overlay on top of the char grid or should there be a 1 pixel gap between chars like in the char selector? i’d imagine no gap is better for drawing..?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Esshahn** [comment]
Yes, that's what I decided to go with for Spritemate, too.

**Comment by nurpax** [comment]
Something like this, maybe?  It's a bunch of white SVG lines blended on top of the canvas with an opacity=0.4 div.

<img width="939" alt="screen shot 2018-08-11 at 12 34 34 am" src="https://user-images.githubusercontent.com/297823/43982395-61439fae-9cfe-11e8-994d-8b87a8f4db51.png">

**Comment by Esshahn** [comment]
One note: v3to suggested for Spritemate to have vertical and horizontal divider lines in the grid, making it easier to plan the layout. It was an easy thing for me to implement, maybe it works for Petmate, too.

![screenshot 2018-08-11 um 14 29 33](https://user-images.githubusercontent.com/434355/43991722-5d5d197c-9d73-11e8-9798-3181ab2f5759.jpg)
