### ISSUE TITLE
Emulate a C64 to some loose degree of accuracy that would be enough to allow importing PRGs generated by the majority of PETSCII editors

### ISSUE THREAD

**Issue by andyherbert** [nurpax/petmate#162]
Yes, it might seem overkill, but it's no less ridiculous than, say, running VICE so that you can dump the memory in the debug monitor through telnet, then expose the character and colour parts of the memory which is the only automated way to do this currently.

**Comment by nurpax** [comment]
There is an easier way than memdumping it out of VICE though. You should be able to load the prg into VICE, save a screenshot as png and then use png import in Petmate. 

Running some sort of 6502 emulator to decode the prg bits into display and reading the screen and color rams would work. But it’s not a small thing to add. 

Some prgs (like those exported by Petmate or Marq’s PETSCII) would be somewhat easy to support by detecting that the prg follows a common code template and then simply loading screen and colors from a fixed file offset. This won’t work for prgs that are not ”template generated” or for stuff like exe packed prgs.

**Comment by Esshahn** [comment]
recommend closing as currently out-of-scope.
