### ISSUE TITLE
Choose different outline color for a defined brush opposed to an empty one

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#163]
![Bildschirmfoto 2019-08-29 um 21 10 01](https://user-images.githubusercontent.com/434355/63969091-64ba7f00-caa1-11e9-874b-b7684206cc5d.png)

When using the brush, it is impossible to tell if the brush is currently an empty char ($20) or undefined. Both states are represented with the green border as shown above.

Suggestion: when no brush is defined, the border outline could be e.g. white or grey.

**Comment by nurpax** [comment]
Now this is a low hanging fruit feature req if there ever was one 👍

**Comment by nurpax** [comment]
@Esshahn Do these colors look OK to you?

![petmate-brush](https://user-images.githubusercontent.com/297823/64132674-2b07b200-cdda-11e9-8646-d79311df0c9f.gif)

**Comment by nurpax** [comment]
I chose "green" for the empty/selecting color because I thought it's useful to be able to tell whether we're selecting a brush or painting.

**Comment by Esshahn** [comment]
perfect!!
