### ISSUE TITLE
Export to GIF Sequence,timing textbox should be larger and support larger time entries

### ISSUE THREAD

**Issue by wbochar** [nurpax/petmate#165]
Export to GIF Sequence, timing textbox should be larger and support larger time entries

If you want a slideshow and try to enter something like 3800 - the textbox is not large enough or fails to expand to view what the user types.

**Comment by nurpax** [comment]
Hopefully this is better

![image](https://user-images.githubusercontent.com/297823/65906503-61315500-e3cb-11e9-8f88-7ecbe619f07b.png)

**Comment by wbochar** [comment]
Awesome :)

**Comment by nurpax** [comment]
Fixed by https://github.com/nurpax/petmate/commit/50ed598114aeba6b4ea3330f1ec663d57eedab44
