### ISSUE TITLE
Find a cool name for your editor ;)

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#17]
how about PETMATE and we bundle our projects as one productivity suite? :D

**Comment by nurpax** [comment]
I like Petmate. Unless a better suggestion emerges, I think I’ll go with this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Esshahn** [comment]
Brilliant! I'd love Petmate and had that name in mind already, but hesitated to propose it ;)

**Comment by Esshahn** [comment]
Hahaha, just read the issue again and realized I DID suggest Petmate.
Man I'm so lame haha!

**Comment by nurpax** [comment]
The name is so awesome that you couldn’t resist suggesting it twice. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Esshahn** [comment]
HAHAHA! Closing! :D

**Comment by nurpax** [comment]
I’ll keep this open so that it stays on my todo list. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
