### ISSUE TITLE
Zoom levels

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#18]
I use a highres screen at work, where the editor is quite small. At home I use a Macbook Air with lowres, so there it's quite big.

Would be great to be able to set some zoom levels

**Comment by nurpax** [comment]
Maybe size the contents to window size using a global scale for all components? My css isn’t very responsive so sizing each component separately would need more work.

**Comment by Esshahn** [comment]
Whatever you find the simplest/fastest to do will work :D

**Comment by Esshahn** [comment]
Zoom levels for

* thumbnails
* canvas

could now easily be stored in your new menu:

![bildschirmfoto 2018-07-27 um 11 40 00](https://user-images.githubusercontent.com/434355/43314020-fa7277ea-9191-11e8-8463-a195885703a2.png)

* Increase thumbnail size (CMD SHIFT +)
* Decrease thumbnail size (CMD SHIFT -)
* Increase canvas size (CMD +)
* Decrease canvas size (CMD -)

**Comment by Esshahn** [comment]
To give you an idea about the size of Petmate versus Petscii.
Maybe there's a cheap way to have zoom, like scaling the whole container in CSS or something?
It takes quite some precision to hit the right positions or select a color.

![screenshot 2018-08-13 um 10 59 12](https://user-images.githubusercontent.com/434355/44022541-2e573290-9ee8-11e8-9bdf-2d522eed927b.jpg)

**Comment by nurpax** [comment]
Yes my plan is to use css. The layout is sort of responsively designed anyway so it shouldn’t be super hard to do.

**Comment by nurpax** [comment]
This is done.  But @Esshahn should perhaps beta test and see how it feels like (see Twitter DMs).

**Comment by Esshahn** [comment]
Zooming works like a blast. Absolutely amazing, super smooth - well done.

I'd still recommend using the menu bar for the following:

* Zoom to original size (320x200)
* Zoom 200%
* Zoom 400%

If that is possible with the current approach (I have a hunch it might be a PITA).
If it's not a low hanging fruit - skip it.

**Comment by nurpax** [comment]
One option would be to have an option in settings that says "snap canvas scale to integer pixel size" so that scale would only change like 1x, 2x, 3x, 4x.  This would retain 1x1 pixels without scaling artifacts.

When resizing the window, it'd choose an integer scale factor that's closest to matching the current window size.
