### ISSUE TITLE
GIF export limited to 64 frames

### ISSUE THREAD

**Issue by ellocotheinsane** [nurpax/petmate#181]
Hello,

when trying to export a gif animation with more than 64 frames an error occurs when writing the file. Saving in other formats works fine but GIF export writes a 0 byte file. If the number of frames is reduced below 64, saving works again.

Please fix in an upcoming version if possible.

Thank you for creating a great tool!

**Comment by nurpax** [comment]
Thanks for reporting it! It’s most likely because of this https://github.com/twolfson/gif-encoder/issues/10

I’ll find a way to fix it for the next release.

**Comment by nurpax** [comment]
Fixed in 0.8.1.
