### ISSUE TITLE
Exporting an executable with a custom charset

### ISSUE THREAD

**Issue by kiwanowski** [nurpax/petmate#183]
When I export the image as an executable all the custom characters I have imported go back to the stock ones.

**Comment by nurpax** [comment]
Sorry about that, it's definitely broken.  

I'll fix this in a later version.  

In the meantime, you should be able to work around this by exporting your art as "standalone asm" and compiling the produce .asm file into a .prg.  I fixed this path to support custom charsets in Petmate 0.8.1.

Most likely I'll replace the current binary file template .prg exporter with the code from .asm export and compile the produced assemble into a program within Petmate.  I can simply link in c64jasm to do this.

**Comment by nurpax** [comment]
Should be fixed by 5d18a981afc11b76a3e39bba1be9c958dc03d030.  Looks like I can release this pretty soon.

**Comment by nurpax** [comment]
Shipped in v0.8.2!  Thanks for filing the bug!
