### ISSUE TITLE
REQUEST: Version information / About

### ISSUE THREAD

**Issue by wbochar** [nurpax/petmate#186]
I couldn't find version information in app, is there a way to see what version I am running?
You should add an about screen, with your name and the application version number. You do good work, so put some credit in app :)

**Comment by nurpax** [comment]
You're not the first one to ask.  The macOS version in fact has this, but Windows and Linux don't.  I'll definitely add it some day :).

**Comment by nurpax** [comment]
Will be implemented when I switch to Electron 8.0.  This supports an about window out of the box on all platforms.

**Comment by nurpax** [comment]
This will be included in the next Petmate version.  It's already in master, just need to close a couple of other bugs before I make the next release.
