### ISSUE TITLE
REQUEST: Support for the .pet file format

### ISSUE THREAD

**Issue by MarkkuR** [nurpax/petmate#202]
There's now this tool https://csdb.dk/release/?id=198395, which lets you extend pics to the borders. For PETSCII it only supports its own .pet format, however. Luckily it's very simple and well documented, a few extra bytes plus the char/color data.

**Comment by nurpax** [comment]
Sounds pretty easy to add.  Where can I find the .pet format docs?  I couldn't find online docs or a GitHub page for the tool..

**Comment by manuelvio** [comment]
I'll copy this here for reference, .pet format is described in the formats.txt file included in the distribution. 

```
Binary file with a .pet extension that includes the following information, without any padding:
        - 1 byte: screen width in chars (40 for whole C64 screen)
        - 1 byte: screen height in chars (25 for whole C64 screen)
        - 1 byte: border color ($D020)
        - 1 byte: background color ($D021)
        - 1 byte: 0 for uppercase PETSCII, 1 for lowercase PETSCII
        - <width * height> bytes: video RAM data
        - <width * height> bytes: color RAM data
```

**Comment by manuelvio** [comment]
Ok, the exporter works, time for a PR :)
![seven nation raster](https://user-images.githubusercontent.com/796799/105898113-5adfd700-6019-11eb-8ed7-e8c9c4c2e333.png)
