### ISSUE TITLE
Upper/lowercase omitted with .c files

### ISSUE THREAD

**Issue by MarkkuR** [nurpax/petmate#203]
It looks like when exporting to PETSCII's .c format the uppercase/lowercase ("shifted") property is neither saved nor loaded. The last line should look like this:

// META: 40 25 C64 upper
or:
// META: 40 25 C64 lower

This is effectively a non-issue, as the chars are loaded correctly anyway and it's easy to change the case, but anyways.

**Comment by nurpax** [comment]
Indeed.  When I implemented this export path, Petmate only supported uppercase and I never fixed all the exporters/importers to deal with shift correctly.

Export would be easy to handle here:

https://github.com/nurpax/petmate/blob/master/src/utils/exporters/index.ts#L63

I'll try to get these fixed for the next release.  I'm planning that version to handle .pet, Manuel's grid fixes and this issue.
