### ISSUE TITLE
Color palette selection

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#21]
Would be cool to be able to choose e.g. Colodore, VICE, pepto color configurations

**Comment by Esshahn** [comment]
you can take the color settings for the ones above out of the spritemate repo if you like

**Comment by Esshahn** [comment]
````
"colodore": 
              [
                "#000000","#ffffff","#813338","#75cec8",
                "#8e3c97","#56ac4d","#2e2c9b","#edf171",
                "#8e5029","#553800","#c46c71","#4a4a4a",
                "#7b7b7b","#a9ff9f","#706deb","#b2b2b2"
              ],
              "pepto":
              [
                "#000000","#ffffff","#67372d","#73a3b1",
                "#6e3e83","#5b8d48","#362976","#b7c576",
                "#6c4f2a","#423908","#98675b","#444444",
                "#6c6c6c","#9dd28a","#6d5fb0","#959595"
````

**Comment by nurpax** [comment]
Done.. I added "petmate" (I don't remember where this came from, maybe vice?), "colodore" and "pepto".  If you have more, let me know.

If you find some issues with this when you try the next build (when I make on), then let's file new bugs and keep this closed.
