### ISSUE TITLE
Cursor keys for character selection

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#22]
Use the cursor keys to navigate and select a character

**Comment by nurpax** [comment]
see https://github.com/nurpax/petski/issues/25

**Comment by Esshahn** [comment]
With multiple screen support now in, I'd vote for using the cursor keys for screen switching. At least for me something of greater importance

**Comment by nurpax** [comment]
Maybe a,w,s,d for char selection?  Added left/right for screen selection just now.  Char selection is pretty common too, maybe more common than screen selection.
