### ISSUE TITLE
escape key should cancel a block

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#23]
It feels a little cumbersome to click on the second level cut icon when I want to draw again after using the block copy tool. 

I recommend that hitting the escape key should have the same functionality, automatically selecting the draw tool again

**Comment by nurpax** [comment]
requires plumbing work from https://github.com/nurpax/petski/issues/25

**Comment by Esshahn** [comment]
I was thinking that hitting escape should also set the drawing pen active again (so whatever goes wrong or wtf's the user, escape makes everything confusing go away), but defaulting to the brush might work either.

I don't really get the 2 functionalities for the brush (the cut symbol hidden on mousedown). Is it needed?

**Comment by nurpax** [comment]
Hmm, I thought it’d be good to just reset the brush selector. If you selected a slightly wrong region, you can esc and try again.
