### ISSUE TITLE
cleanup boilerplate project (removing unstable parts, typeflow, etc.)

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#24]

**Comment by nurpax** [comment]
https://github.com/pbarbiero/enhanced-electron-react-boilerplate

at least once my upgrade PR goes in

**Comment by Esshahn** [comment]
probably too far into the process to make that change, right? Close?

**Comment by nurpax** [comment]
will do this at some point. the current boilerplate is a pita to work with

**Comment by Esshahn** [comment]
will it get harder with every line of code added? Then I'd recommend putting it in the current release and be done with it ;)

**Comment by nurpax** [comment]
no, most code will drop in cleanly 1:1 into the new project structure. just need some git gymnastics to retain version history

**Comment by nurpax** [comment]
OK so I tried doing this but... it got hairy.

I think I'll just clean up some odd parts of the current boilerplate and call it a day.  I'm especially unhappy with HOT loading because it breaks things more than helps.

**Comment by nurpax** [comment]
This was done for 0.5.0 and boy did I get rid of a lot of cruft.
