### ISSUE TITLE
don't let user close tabs or load a file when there are unsaved changes

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#33]

**Comment by Esshahn** [comment]
I'd recommend doing it as unintrusive as possible, e.g. having an "Are you sure?" dialog.
Would then become a setting in the preferences later on.

**Comment by nurpax** [comment]
I thought just that usual ”The current screen contains unsaved changes. Continue with import?”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Esshahn** [comment]
putting this to 0.7 as I think this is a low hanging fruit that might turn out to be of great help
