### ISSUE TITLE
"Clear canvas" broken

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#37]
0.0.4 build has the "clean canvas" icon broken, nothing happens when being clicked.

Reproduce
* draw something
* click trash can

(also I'd recommend a different icon than the trashcan, it's so negative ;) )

**Comment by nurpax** [comment]
LOL, how did I manage to break that! 🙄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nurpax** [comment]
Fixed.  But not sure what'd be a good icon to use instead of trashcan.  If you can suggest one from https://fontawesome.com/, would be great. :)
