### ISSUE TITLE
Reduce file selection to importable files only

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#38]
Not sure if that's possible with the tech setup, but it would be nice to only see the files in the open dialog window that actually can be imported

![bildschirmfoto 2018-07-27 um 09 38 22](https://user-images.githubusercontent.com/434355/43309278-a61f2eb6-9184-11e8-9362-b5d689b60593.png)

Also, I love when the app actually identifies the correct file format and the user does not have to use the dropdown menu to decide

![bildschirmfoto 2018-07-27 um 09 34 48](https://user-images.githubusercontent.com/434355/43309314-c1fd0ce8-9184-11e8-9d3f-fab5219c5a5d.png)

Having the dropdown it would make sense if it acts like a selection filter for the file view, showing only the importable files.

Also I would show the file extension for Petmate in the dropdown (and it's probably Petmate, not PETSCII, right?).

**Comment by nurpax** [comment]
I think .petmate workspace load will probably use a separate dialog with only .petmate load. 

petscii file in import is the old .petski format which i kept for testing purposes. it will be removed. 

everything you ask still makes sense tho, need to look into how to make the open dialog better. hopefully it’s possible on mac/electron. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nurpax** [comment]
I'll take a look if it'd be possible to show in "black" (and not grayed) all supported formats without having to select between different import file formats.

>Having the dropdown it would make sense if it acts like a selection filter for the file view, showing only the importable files.

In my case it actually does that.  See attached (shows the only .c file as black, everything else grayed out)
<img width="627" alt="screen shot 2018-07-27 at 11 00 48 pm" src="https://user-images.githubusercontent.com/297823/43344071-2f0ae000-91f1-11e8-8fa8-41b40f02183a.png">
