### ISSUE TITLE
Simplify load/save/file icons and metaphor

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#40]
![bildschirmfoto 2018-07-27 um 10 09 21](https://user-images.githubusercontent.com/434355/43309494-36cc0466-9185-11e8-8793-65d1da614b35.png)

As you already mentioned, I agree that this might be a bit of an overkill. What comes to mind first:

* what is a workspace (and how is it different from loading/saving a file? And why should the user know/bother?)
* why is loading a workspace a folder, but saving a floppy?

Ideally, there's 
* load
* save

where load smartly identifies the file format (Marq, Petmate etc.) and asks if you want to merge the data with the current data (if there's any) and save asks you for the desired export format.

(I know I'm greedy here :) )

**Comment by nurpax** [comment]
Closing this. Hopefully my explanation makes sense and the UI with app menus also make the save vs. export distinction more clear.
