### ISSUE TITLE
Investigate using a different pixel ratio

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#42]
Just a sidenote, I noticed to things:

* Colors in PETSCII are more likely resembling a real C64 (they are duller and less funky though)
* Pixel height is different (and I currently can't tell which one is closer to the original)

![bildschirmfoto 2018-07-27 um 10 31 26](https://user-images.githubusercontent.com/434355/43310637-6f2fac4c-9188-11e8-952c-539190f6e3b5.png)

**Comment by nurpax** [comment]
Maybe the pixel aspect rationis not 1:1 on a real C64? Petmate assumes 1:1. 

Palette: I guess this will be covered by palette selection?

**Comment by Esshahn** [comment]
Correct, the pixel ratio is a bit off from 1:1
http://codebase64.org/doku.php?id=base:pixel_aspect_ratio

**Comment by nurpax** [comment]
I have some divs hardcoded two vertical/horizontal 2x scaling.  I'll take a look at the pixel aspect ratio once I look into screen zoom levels.

**Comment by Esshahn** [comment]
Done:
* colors will be handled by the palette settings

Open:
* find out if the pixel ratio of 1:1 is sufficient (compare to other C64 tools)

**Comment by Esshahn** [comment]
closing as this might be tough to implement with little benefits.
