### ISSUE TITLE
screen support: duplicate screen

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#46]
I noticed one crucial feature missing for my personal workflow: I always work with copies/workstages, so I regularly duplicate a screen.

* right click on screen could show options (delete, duplicate)
* could also be a separate menu entry
* when duplicating a screen, the editor should switch to the newly created screen

**Comment by nurpax** [comment]
Makes sense. I’ll add this. This could also not rely on right mouse click (in case I decide to make a pure web version) by adding an overlay on hover on top of the top screen selector button. The overlay could have an x for delete, [[]] for duplicate (on mobile so excuse my ascii art icons). 

The screen ops are not undoable but I guess we can live with that for now.

**Comment by nurpax** [comment]
The x button on hover could be dangerous tho. User might accidentally click it when selecting a screen.

**Comment by nurpax** [comment]
@Esshahn is this acceptable: https://www.youtube.com/watch?v=b3cBtFrmoZs
