### ISSUE TITLE
Text tool

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#51]
It is somewhat cumbersome to enter text now - you have to pick the chars one by one, move back the cursor to the canvas, pick another char etc.
There could be a mode, where you can just click on the canvas for a start point, and just type.
Obviously it should turn off all the other keyboard shortcuts (like any other text tool in the regural gfx editors)
Not that important though, I guess it is relativly rare to use too much text in PETSCII gfx.
I don't know maybe are there "hardcore" petscii graphichians, who learned on the c64 and just type non-letter characters too (with c64-like shortcuts)?... :-?

**Comment by nurpax** [comment]
I very much agree, was on my wetware todo list but forgot to file an issue here.

**Comment by nurpax** [comment]
Here we go: https://youtu.be/Khh8ctzQxTo

This feature feels awesome.. btw.  :)

**Comment by nurpax** [comment]
I wanted to use 'T' icon for selecting the text tool but couldn't find such an icon in Fontawesome.  I guess I could just use a large 'T' text string.

**Comment by Esshahn** [comment]
really well done! congrats!
