### ISSUE TITLE
Remove secondary icon for brushes

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#53]
I regret to inform you about this very serious bug.
All the other tools in the left toolbar have a tooltip except the brush tool. It is pretty sad.

Is there a more serious category for bugs than a "crash" bug?
Because this issue is definitely that.

;)

**Comment by Esshahn** [comment]
(issue renamed for clarity)

* remove the secondary (mousedown) icon from the tools menu as ESC handles that now
* add tooltip to primary icon

![screenshot 2018-08-04 um 10 28 24](https://user-images.githubusercontent.com/434355/43674239-258d52de-97d1-11e8-8303-17ae8a25f7d1.jpg)
