### ISSUE TITLE
better icon for "clear canvas"

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#57]
preferably choose one from fontawesome.com

**Comment by Viza74** [comment]
"file" - rotated 90?
"sticky note"?
some from the different variantions of "times" X?
maaaaaybe "tint-slash"?

Or maybe just delete that tool?
It's placement is way to prominent for it's function anyway - you basically never need it.
Also the "clear canvas" action concerns the whole screen, so it could be moved to the right click menu in the screens toolbar too.

**Comment by nurpax** [comment]
<img width="200" alt="screen shot 2018-07-31 at 12 09 49 am" src="https://user-images.githubusercontent.com/297823/43423821-17511404-9456-11e8-96ff-a312012fc0d3.png">

I went with the cute broomstick icon for now :)

Agreed that it may be a bit redundant now..  The make a new empty screen, it's enough to click on the plus icon on the top bar.

**Comment by nurpax** [comment]
Off-topic: the PM logo is WIP from Cal.  Not sure if this is the one we go with.

**Comment by nurpax** [comment]
Also moved undo/redo to top.  I think they're better there than between clear and the rest of the drawing operations.

As for clear..  A rectangle clear would be useful.  Maybe it'd make more sense to add clear rect, colorize rect tools and get rid of clear canvas.
