### ISSUE TITLE
mirror brushes

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#62]
(compare with Marq's tool).
A brush should be able to be mirrored horizontally and vertically.
I use that functionality quite often.

**Comment by nurpax** [comment]
Yes, this will be added. Marq has a “smart mirror” which also rewrites the chars to find pixel wise mirrored screencodes.

**Comment by nurpax** [comment]
Do you know if PETSCII does more than just bit exact reverse x/y matching for "smart flipping"?

I implemented it this way: https://gist.github.com/nurpax/103d675b532c3c8c9b6580900734160f and it works quite well for a lot of content, but not for everything.

**Comment by nurpax** [comment]
Mirroring done but rotate might not be too bad either.  I noticed that it's handy if you're painting some box graphics.  Also rotate+mirror current char is useful.

**Comment by Esshahn** [comment]
I'd suggest to close this one as the main task is completed.

**Comment by nurpax** [comment]
yes, if you have the time, file bugs for rotate and a separate issue for rotate/mirror currently selected char.  the groundwork for doing the latter part is done.
