### ISSUE TITLE
Menu Save wording

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#65]
When clicking on "Save...", Petmate saves the file and does not ask for anything.
I think convention is, that "..." is only used if more modals/decisions are to be made.
Therefore I would recommend to just write "Save".

![screenshot 2018-08-02 um 12 04 26](https://user-images.githubusercontent.com/434355/43577580-82ef31ee-964c-11e8-88a6-4e9750dd1152.jpg)

**Comment by nurpax** [comment]
Great! i didn’t know about this convention. Will clean it up.
