### ISSUE TITLE
logo idea

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#66]
Hey, doodled around a bit about a Petmate logo.
Maybe you like it...
Bonus: could be a nice 3D printed object on your desk :D 

![screenshot 2018-08-02 um 12 07 13](https://user-images.githubusercontent.com/434355/43577628-a7f4c3f0-964c-11e8-805a-28cd87500af5.jpg)

[logo.petmate.zip](https://github.com/nurpax/petmate/files/2253038/logo.petmate.zip)

**Comment by Esshahn** [comment]
Btw don't worry if it's not your thing! I had fun making it :D

**Comment by nurpax** [comment]
It’s cool tho. Didn’t have the time to plug it in yet. Wanna send a PR that plugs it in?

yarn
yarn dev

to run. Icon is in app/assets/appicon.png. See gitlog for the png to see where to tweak layout if needed. 

:)

**Comment by nurpax** [comment]
thanks for https://github.com/nurpax/petmate/pull/67!

<img width="155" alt="screen shot 2018-08-02 at 10 44 30 pm" src="https://user-images.githubusercontent.com/297823/43606983-8b1c1d42-96a5-11e8-99c2-689fee8c8821.png">

looks like so.  does it look like it's a little stretched vertically?

not sure which one I prefer.  I'll let this sit a bit. :)

**Comment by Esshahn** [comment]
It does look better at a bigger size. Hmm. Could be worth doing a version as vector logo, not PETSCII. Anyway, thank you for trying it out! And feel free to remove it anytime :)

**Comment by nurpax** [comment]
Yes, it definitely looks better bigger.. Doesn't need to be PETSCII IMO.. Or if it's petscii, then maybe it should go full on PETSCII so that it's sort of obvious it is what it is.

**Comment by Esshahn** [comment]
I hipsterified the logo for you :D 

![hipster-mate](https://user-images.githubusercontent.com/434355/43611738-6d7c8b5a-96aa-11e8-89ec-9f9f202a7761.png)

**Comment by nurpax** [comment]
LOL!!  We should turn this into a startup and earn some big $$$s

**Comment by Esshahn** [comment]
would be a nice app icon now. damn maybe I need to rename Spritemate to Pritemate :D

**Comment by nurpax** [comment]
I'd go with this logo.  My only problem is that I don't really have any image editor installed (I tried many but they all somehow sucked, apart from PS maybe) so adjusting the source image to the various resolutions that I need for icons would take me quite a bit of time. But I'd definitely want this as the Electron logo makes Petmate look kind of n00bish.

**Comment by Esshahn** [comment]
If you like and and want to use it, I will provide any files needed for you. Happy to do so actually.

As for image creation, I've completely switched to Sketch. It seems underpowered when you're used to Illustrator etc, but that's really it's strength. It does what it does really well and quickly has become the defacto standard for screen design. This logo was done with it.

As for pixel based image editing, Photoshop is still without alternative. I just quit my monthly subscription again, probably for the millionth time now. I have a deep love/hate/hate relationship with Adobe software.

Affinity Photo and Designer on the Mac are both very powerful and I always try to use these first. But for creating multicolor images for the C64 I need a feature that only Photoshop has right now: amorphic pixels. 

I'm happy Marq just released a new version of Multipaint, but honestly its extremely limited when you're used to Photoshop.

**Comment by Esshahn** [comment]
closing in favor of new issues
