### ISSUE TITLE
Rotation for brushes

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#70]
Done:

* mirror H
* mirror V

Open:

* rotate by 90 degrees

**Comment by nurpax** [comment]
Note: realized that at least for rotation, the rotation code cannot keep rotating the same brush contents 90 degrees at a time.. Rather it needs to capture the original brush and then rotate 90, 180 and 270 from the original source.  Otherwise switching between these rotation angles will be lossy.

**Comment by Esshahn** [comment]
Exactly
