### ISSUE TITLE
Prepare assets for Petmate logo

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#73]
Create assets for Win/Lin/Mac

* App Icon
* Documentation and other places we might want to use the logo
* Twitter (?)
* Other?

If you have any experience already about the requirements, let me know, otherwise I will do some googling.

**Comment by nurpax** [comment]
I know very little about these assets.  I use this boilerplate: https://github.com/chentsulin/electron-react-boilerplate - not sure if it contains any docs.  But maybe just take a look at Electron docs.

**Comment by nurpax** [comment]
The Electron requirements might be the most strict.  Twitter, docs, etc, is easier since we control our own path there.

**Comment by Esshahn** [comment]
I will follow this tutorial to get me started: https://www.christianengvall.se/electron-app-icons/

**Comment by Esshahn** [comment]
Howto:
https://www.christianengvall.se/electron-app-icons/
https://www.christianengvall.se/electron-packager-tutorial/

Files for Browser/Electron:
[icons.zip](https://github.com/nurpax/petmate/files/2260247/icons.zip)

Folder PNG contains several sizes that can be used for Twitter, Docs, etc

**Comment by nurpax** [comment]
Very nice!  I came here to say no, I will do this later.. and then noticed there's a zip attachment that contains everything I need.  I'll try and plug this in soonish.  Maybe once the color palette selection is checked in.

Another "productization" change that I'd need to do at some point would be to setup my Apple developer ID correctly in the Petmate build.  I do have one for iOS App store so I'd imagine I can use that for Petmate too.  This would get rid of the annoying nags when running a downloaded version.  Same goes for Windows where the Windows installer loudly complains that one should absolutely NOT install this software, which is not a great onboarding experience.  But this will come later, maybe for 1.0 :)

**Comment by nurpax** [comment]
<img width="652" alt="screen shot 2018-08-05 at 9 29 54 pm" src="https://user-images.githubusercontent.com/297823/43688756-bc70781c-98f7-11e8-8ba5-a55d7c570165.png">
