### ISSUE TITLE
Custom palette order preferences resets on file load

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#75]
If I create some custom palette color orders in the prefrences, next time I open petmate the order is still there, but if I open any files, the order resets to the dfault in all four slots.

**Comment by nurpax** [comment]
Yes, I think I fixed this here https://github.com/nurpax/petmate/commit/cf0367f6a8f103da1cce68c0fbe29a54b3403b87 but it's not in any released binary version yet.

**Comment by nurpax** [comment]
This is in 0.2.2.  0.2.2 however breaks .png export.  Which I just fixed. 

I will release these changes with tool key shortcuts (and maybe char/color pick, let's see)
