### ISSUE TITLE
Tooltip text for draw modes

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#76]
Take these as a suggestion or to get refinement started:

![screenshot 2018-08-12 um 10 55 12](https://user-images.githubusercontent.com/434355/44000337-356b8088-9e1e-11e8-8507-ae087b7ceb42.jpg)

- Character & Color
- Color only
- Character only

**Comment by nurpax** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/TRGsStbCM7w/0.jpg)](https://www.youtube.com/watch?v=TRGsStbCM7w)

**Comment by nurpax** [comment]
@Esshahn I wonder if the brush icon (or brush tool name, even) is a bit confusing.  At least the icon might be better served with the usual crop and/or select area icon (e.g. https://fontawesome.com/icons/crop?style=solid)

**Comment by Esshahn** [comment]
Agreed.
Not so sure about the crop icon (as we're not cropping).
Maybe something more like these?
clone: https://fontawesome.com/icons/clone?style=regular
stamp: https://fontawesome.com/icons/stamp?style=solid

**Comment by nurpax** [comment]
I like the stamp icon.  I'll switch it to that.  Should we rename the tool to stamp or keep it as brush?

**Comment by nurpax** [comment]
<img width="154" alt="screen shot 2018-08-14 at 12 49 30 am" src="https://user-images.githubusercontent.com/297823/44060044-f5d85e8e-9f5b-11e8-89a9-fea76384ebf2.png">

**Comment by nurpax** [comment]
I tried changing it to stamp.. but when I was updating the docs, somehow brush just felt better than "stamp" or "stencil".  Maybe I'll just keep it as it is.
