### ISSUE TITLE
shift tool

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#81]
This might be more of a rare use case and the brush covers for 90% of the cases already. 

Provide a (likely menu bar only) option to:
- shift content of a screen up/down/left/right

This comes in handy when full screen art needs to be moved e.g. to the left one character. You can't do this with the brush easily, only by using and extra screen as a buffer (try it out, then you get what I mean).

Spritemate has this too. It was super easy as I just rotated the pixel array. Might be a low hanging fruit.

Suggestion:
In EDIT menu:
* shift left
* shift right
* shift up
* shift down
* flip horizontal
* flip vertical

**Comment by nurpax** [comment]
Shifting done but need to add the menus for Windows/Linux still. (The code is duplicated and I didn't want to start testing on Windows yet.)
