### ISSUE TITLE
Set default character to inverted space

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#83]
Ok this is kind of a luxury, but it helps for two use cases:

- new users trying out the app for the first time
- heavy testers (like me)

Suggestion:

- set the default character not to the normal space, but inverted space

![screenshot 2018-08-12 um 19 50 29](https://user-images.githubusercontent.com/434355/44004813-2c0a7a6c-9e69-11e8-9270-fa476941779e.jpg)

Reason:

- you can start drawing right away without picking a different character first

PS:

- thank me later for it :D

**Comment by nurpax** [comment]
I agree. I don’t know why I didn’t do it earlier :)
