### ISSUE TITLE
Colorize empty cells?

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#84]
This is not a bug and I totally get it from the technical side.
It just occurred to me that this might not be the desired behavior.
Or maybe it is. Would like to get feedback from @nurpax and @Viza64

What happens:
- when colorizing an empty cell (which technically is just $20 character), you would not see it, but it does indeed change the color
- but you can make the color visible by drawing with a non-empty character on that area

It acts like color ram and screen ram actually. Please check out the video attached.

Question is: should $20 generally be treated as "transparent" and not accept color when there's nothing to see?

[colorizing.mov.zip](https://github.com/nurpax/petmate/files/2281189/colorizing.mov.zip)

**Comment by nurpax** [comment]
It’d be nice to make that assumption. It might be broken by custom charset loading. (space might not be at $20). Otoh charsets most likely alwwys have an empty char do could search for it from the font bitmap.

**Comment by Esshahn** [comment]
Good thinking with the problems that might arise later with custom charsets.
And as mentioned already, it does behave totally correct.
Marq's editor does not have this "issue", as he does not feature a "character only" draw mode.
With what you just noted I think it might be a good idea to leave it as is currently.
What do you think?

**Comment by Esshahn** [comment]
Closing this. It will come up again if this is a problem in the future, but let's keep the backlog clean.
