### ISSUE TITLE
show cursor x,y coordinates

### ISSUE THREAD

**Issue by nurpax** [nurpax/petmate#86]
gathering user feedback: 

some folks want to see the current mouse x,y coordinates (in char coords, of course)

agreed that this is probably helpful to be able to position some other elements like sprites on the screen.

**Comment by Esshahn** [comment]
I never missed the coordinates, but I do have use for showing the char number like $122, that comes in handy when coding, e.g. collisions.

Could all fit in a status bar of the app or below the character selection maybe
