### ISSUE TITLE
show char code of selected character

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#88]
As discussed in #86 

Would be great to see the char code of the selected character.
Also: show char code of the character the mouse is hovering over, both in canvas and in char selection.

![screenshot 2018-08-13 um 10 45 39](https://user-images.githubusercontent.com/434355/44021823-13c25416-9ee6-11e8-8b0a-1473a1b594b5.jpg)

left side under the canvas 
- shows x/y coordinates of character/mouse
- shows the character value the mouse is hovering over (mouse can't be seen on the screenshot, sorry)

right side under the char selector
- shows decimal/hex value of the selected char

**Comment by nurpax** [comment]
@Esshahn something like this for the editor canvas: https://youtu.be/nXFo2XH7Co4?

**Comment by Esshahn** [comment]
Can you make the char code in character selection react on hover, too, like the canvas one?

![screenshot 2018-08-16 um 11 03 31](https://user-images.githubusercontent.com/434355/44199363-2b3bfd80-a144-11e8-8d92-e8cd73efddf6.jpg)

**Comment by nurpax** [comment]
https://youtu.be/F9ZJ5nW1ASk

The code's ready.  If it's not confusing, might as well check that in.  I'm not sure which is better.  I think I might slightly prefer the no hover variant.

**Comment by nurpax** [comment]
I checked in the hover version.
