### ISSUE TITLE
Bigger thumbnails

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#91]
Now that you've freed up so much unused space at the top (looking great btw!), it would be wonderful to make the thumbnails bigger. 200% might be too much, but it would fit. 

![screenshot 2018-08-16 um 11 07 01](https://user-images.githubusercontent.com/434355/44200075-ffba1280-a145-11e8-966c-9b1f93556648.jpg)

**Comment by nurpax** [comment]
Double size fits but looks a little distracting.  I tried 1.5x, this seems ok to me.  

Here's a comparison.  Left is new, right is old.

<img width="732" alt="screen shot 2018-08-17 at 12 27 01 am" src="https://user-images.githubusercontent.com/297823/44236068-7130aa00-a1b4-11e8-903f-b2feb5397cfc.png">
