### ISSUE TITLE
Change size and position of color picker

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#93]
Suggestion: now that the character info was added, layout got a bit wacky for my OCD

![screenshot 2018-08-16 um 12 11 19](https://user-images.githubusercontent.com/434355/44202929-b1a90d00-a14d-11e8-881f-36efd114ac4f.jpg)

So how about we solve two things at once: bigger color pickers and cleaner layout?
It could look like this:

![screenshot 2018-08-16 um 12 18 04](https://user-images.githubusercontent.com/434355/44203230-9a1e5400-a14e-11e8-8aa0-bfb3eb94356a.jpg)

**Comment by nurpax** [comment]
![screen shot 2018-08-17 at 12 08 51 am](https://user-images.githubusercontent.com/297823/44235323-c3bc9700-a1b1-11e8-8a2d-f938c221cba4.png)

This is what I have now.  Pretty close to yours but I dropped the borders around color boxes.. because of.. reasons.

**Comment by Esshahn** [comment]
I like reasons!
