### ISSUE TITLE
Closing window makes Petmate unusable (Mac)

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#96]
There are some related issues tracked already, but maybe this is a quick fix:

Problem:
* close the main window
* Petmate is still running, but has no window anymore
* you can't work with it anymore
* clicking on the app icon to restart it does not work either as it is already running
* you need to actively quit the app and then reopen ist

Suggested fixes:
a) do not allow to close the main window
b) when closing the main window, quit the app completely
c) allow to open a new window when window was closed (auto-open with file operations, too)

All three of them would work I guess, and I've seen all of these in other apps as solutions. From UX perspective, I'd go for "b", as this will likely follow the user's initial intention when closing the window.

**Comment by Viza74** [comment]
Duplicate of #47 and maybe #36 ?

**Comment by Esshahn** [comment]
closing as petmate now quits

**Comment by nurpax** [comment]
it does? i must’ve fixed it by accidentally:)

or maybe it crashes and then exits.

**Comment by nurpax** [comment]
Yeah, it's indeed fixed and the code handling this makes sense:

```
app.on('window-all-closed', () => {
    app.quit();
});
```
